name: Deploy on Merge to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 114.129.8.23
          username: root
          key: ${{ secrets.UNIBOT_DEPLOY_KEY }}
          port: 22
          script: |
            set -e

            echo "[1] 🔻 Stop bot service"
            systemctl stop unibot

            echo "[2] 📂 Go to project folder"
            cd /root/UniBot

            echo "[3] 💢 Reset hard & pull latest changes"
            git fetch origin
            git reset --hard origin/main

            echo "[4] 🐍 Activate virtualenv and install requirements"
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            deactivate

            echo "[5] 🚀 Start bot service"
            systemctl start unibot
